### ISSUE TITLE
App crashes when saving a document with custom color spans.

### ISSUE THREAD

**Issue by kitakkun** [kitakkun/NoteApp#5]
## Error log
```
FATAL EXCEPTION: main
Process: com.github.kitakkun.noteapp, PID: 25278
java.lang.NumberFormatException: For input string: "18446462598732840960"
	at java.lang.Long.parseLong(Long.java:736)
	at java.lang.Long.parseLong(Long.java:861)
	at com.github.kitakkun.noteapp.ui.page.editor.editmodel.serializer.OverrideStyleTypeAdapter.read(OverrideStyleTypeAdapter.kt:60)
	at com.github.kitakkun.noteapp.ui.page.editor.editmodel.serializer.OverrideStyleTypeAdapter.read(OverrideStyleTypeAdapter.kt:9)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.github.kitakkun.noteapp.data.DocumentConverter.toOverrideStyleAnchorList(DocumentConverter.kt:26)
	at com.github.kitakkun.noteapp.data.DocumentDao_Impl.getAll(DocumentDao_Impl.java:227)
	at com.github.kitakkun.noteapp.data.DocumentRepository$fetchDocuments$2.invokeSuspend(DocumentRepository.kt:53)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5c237f5, Dispatchers.Main.immediate]
```

**Comment by kitakkun** [comment]
This crash happens because `"18446462598732840960"` does not match the Long data format. It should be `"18446462598732840960L"`. 
By the way, color data can be stored as Integer value because `androidx.compose.ui.graphics.Color` internally convert the Long value to Integer value.

**Comment by kitakkun** [comment]
https://github.com/kitakkun/NoteApp/blob/c0174ae9f87aca5e20098635b3fee9808c05be42/app/src/main/java/com/github/kitakkun/noteapp/ui/page/editor/editmodel/serializer/OverrideStyleTypeAdapter.kt#L31

We need to store color value by `Color.toArgb()` instead of `Color.value`.
This should fix the problem.
